name: 天气数据收集

on:
  schedule:
    - cron: "0 * * * *"  # 每小时运行
  workflow_dispatch:    # 允许手动触发

jobs:
  record-weather:
    runs-on: ubuntu-latest
    env:
      OWM_API_KEY: ${{ secrets.OWM_API_KEY }}  # 在仓库Settings/Secrets中设置
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: 安装依赖
      run: pip install requests
      
    - name: 运行记录器
      run: python weather_logger.py "Foshan" "Beijing" "Shanghai"
      # 添加更多城市用空格分隔

    - name: 提交更改
      run: |
        git config --global user.name 'FireStar0507'
        git config --global user.email '18064625480@163.com'
        git add weather_data/
        git diff-index --quiet HEAD || git commit -m "自动更新天气数据"
        git push
