name: Weather Data Logger

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  log-weather:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cities: ['Foshan', 'Beijing', 'Shanghai']  # 可扩展城市列表
    
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        
    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 记录天气数据
      env:
        OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
      run: |
        pip install requests
        python weather_logger.py "${{ matrix.cities }}"

    - name: 提交变更
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add *.csv
        git diff --quiet && git diff --staged --quiet || git commit -m "自动更新天气数据"
        git push
