name: 天气数据收集

on:
  schedule:
    - cron: "0 * * * *"  # 每小时运行
  workflow_dispatch:    # 允许手动触发

jobs:
  record-weather:
    runs-on: ubuntu-latest
    env:
      OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        # 关键设置：允许后续推送
        persist-credentials: true
    
    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: 安装依赖
      run: pip install requests
      
    - name: 运行记录器
      run: python weather_recorder.py "Foshan" "Beijing" "Shanghai"
    
    - name: 提交更改
      run: |
        git config --global user.name 'FireStar0507'
        git config --global user.email '18064625480@163.com'
        git add weather_data/
        
        # 检查是否有更改
        if [ -z "$(git status --porcelain)" ]; then
          echo "没有变更需要提交"
        else
          git commit -m "自动更新天气数据 [skip ci]"
          git push origin HEAD:${{ github.ref }}
        fi
